program: train_old.py
method: bayes
metric:
  name: val_accuracy
  goal: maximize
parameters:
  num_stages:
    min: 2
    max: 5
  num_layers:
    min: 9
    max: 16
  activation:
    values: ['relu', 'celu', 'selu', 'silu']
  smoothness_factor:
    min: 0.30
    max: 0.60
  time_series_model:
    values: ['MSTCN', 'MSTCN++']
  lr:
    min: 0.0001
    max: 0.01
  num_f_maps:
    values: [8, 16, 32, 64, 128]